version: '3.8'
services:

  web:
    build:
      context: ./
      target: dev
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    environment:
      NODE_ENV: development
    volumes:
      - .:/src

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: